import 'package:ciach/src/candidates.dart';
import 'package:ciach/src/paths.dart';
import 'package:collection/collection.dart';

/// The Dart file generated by `gen-l10n` from the template ARB file, and that
/// ARB file. Both are POSIX paths that are relative to the package root.
typedef Translations = ({String dartFile, String arbFile});

/// Returns the [Translations] whose Dart file declares [candidate], or `null`
/// when there are none. A finding in such a file is report-only, because the
/// message is defined in the ARB file. If the message were removed only from
/// the Dart file, `gen-l10n` would generate it again.
Translations? translationsOf(
  Candidate candidate,
  List<Translations> translations,
  String rootPath,
) {
  final path = relativePosix(candidate.path, rootPath);
  return translations.firstWhereOrNull((t) => t.dartFile == path);
}
