/*
 * AI-Provenance:
 *   model: claude-opus-4-8
 *   harness: Claude Code
 *   plugins:
 *     - lean-ai-provenance
 *   skills:
 *     - mark-ai-provenance
 */

import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:ciach/src/models.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;

/// Directory names that never contain source worth analyzing.
const _skippedDirs = {'.dart_tool', '.git', 'build', '.fvm', 'node_modules'};

/// Filename suffixes produced by common Dart/Flutter code generators.
const _generatedSuffixes = [
  '.g.dart',
  '.freezed.dart',
  '.gr.dart',
  '.config.dart',
  '.mocks.dart',
  '.gen.dart',
  '.pb.dart',
  '.pbenum.dart',
  '.pbjson.dart',
  '.pbserver.dart',
  '.chopper.dart',
];

/// The `.dart` files discovered under the configured root, split by role.
typedef DiscoveredDartFiles = ({
  /// Files whose declarations are scanned and reported as candidates.
  List<String> candidates,

  /// Generated files excluded from [candidates] but still opened to keep the
  /// analysis server's units warm, so a declaration referenced *only* from
  /// generated code isn't misreported as unused. Empty when generated files
  /// are themselves candidates.
  List<String> warmOnly,
});

/// Discovers the `.dart` files under the configured root that should be
/// scanned for declarations, honoring include/exclude globs and
/// generated-file rules.
///
/// Results are returned as absolute file paths, sorted for stable output.
List<String> discoverDartFiles(FinderOptions options) =>
    discoverDartFilesSplit(options).candidates;

/// Like [discoverDartFiles], but also returns the excluded generated files as
/// `warmOnly` (see [DiscoveredDartFiles]) so the caller can open them for
/// reference resolution.
///
/// The warm-only set is deliberately not filtered by include/exclude globs — a
/// reference can live in a generated file the user isn't scanning — though
/// skipped directories (`build/`, `.dart_tool/`, …) are still excluded.
///
/// [configuredGeneratedGlobs] adds to [FinderOptions.additionalGeneratedGlobs]: the
/// generated files the project's own configuration declares.
DiscoveredDartFiles discoverDartFilesSplit(
  FinderOptions options, {
  List<String> configuredGeneratedGlobs = const [],
}) {
  // Already absolute and normalized: `FinderOptions` is the only way in.
  final rootPath = options.rootPath;
  final root = Directory(rootPath);
  final context = p.Context(style: .posix);

  final includeGlobs = [
    for (final pattern in options.includeGlobs) Glob(pattern, context: context),
  ];
  final excludeGlobs = [
    for (final pattern in options.excludeGlobs) Glob(pattern, context: context),
  ];
  final generatedGlobs = [
    for (final pattern in [
      ...options.additionalGeneratedGlobs,
      ...configuredGeneratedGlobs,
    ])
      Glob(pattern, context: context),
  ];

  final candidates = <String>[];
  final warmOnly = <String>[];
  for (final entity in root.listSync(recursive: true, followLinks: false)) {
    if (entity is! File || !entity.path.endsWith('.dart')) {
      continue;
    }

    final absolute = p.normalize(entity.absolute.path);
    // Path relative to root, in POSIX form so globs behave predictably.
    final relative = context.joinAll(
      p.split(p.relative(absolute, from: rootPath)),
    );

    if (isInSkippedDir(relative)) {
      continue;
    }
    if (!options.includeGenerated &&
        (generatedGlobs.any((glob) => glob.matches(relative)) ||
            _isGenerated(
              entity,
              relative,
              options.additionalGeneratedSuffixes,
            ))) {
      warmOnly.add(absolute);
      continue;
    }
    if (includeGlobs.isNotEmpty &&
        !includeGlobs.any((glob) => glob.matches(relative))) {
      continue;
    }
    if (excludeGlobs.any((glob) => glob.matches(relative))) {
      continue;
    }

    candidates.add(absolute);
  }

  candidates.sort();
  warmOnly.sort();
  return (candidates: candidates, warmOnly: warmOnly);
}

bool isInSkippedDir(String relativePath) =>
    p.split(relativePath).any(_skippedDirs.contains);

bool _isGenerated(
  File file,
  String relativePath,
  List<String> additionalSuffixes,
) {
  final name = p.basename(relativePath);
  if (_generatedSuffixes.any(name.endsWith) ||
      additionalSuffixes.any(name.endsWith)) {
    return true;
  }
  return isGeneratedBanner(_readPrefix(file, 2000));
}

/// The banner package:build writes, recognized anywhere near the top.
const _buildBanner = 'GENERATED CODE - DO NOT MODIFY BY HAND';

/// A generated-code banner: "generated" and "do not edit/modify" together in
/// the comments a file opens with, worded as each generator likes —
/// `GENERATED CODE - DO NOT MODIFY BY HAND` (build_runner), `Generated code. Do
/// not modify.` (protoc), `AUTOMATICALLY GENERATED CODE DO NOT MODIFY`
/// (Serverpod), `Autogenerated from Pigeon …, do not edit directly.`, `AUTO
/// GENERATED FILE, DO NOT EDIT.` (ffigen).
final _banner = RegExp(
  r'\b(?:auto-?)?generated\b.{0,200}?\b(?:do not|don.t|must not)\s+(?:\w+\s+)?(?:edit|modify)\b'
  r'|\b(?:do not|don.t)\s+(?:edit|modify)\b.{0,200}?\bgenerated\b',
  caseSensitive: false,
);

/// Whether [source] opens with a generated-code banner. Other than package:
/// build's own, only the leading comments count, and not doc comments, so a
/// hand-written file that mentions one — in its library docs, a string — is
/// still scanned.
bool isGeneratedBanner(String source) {
  if (source.substring(0, min(source.length, 300)).contains(_buildBanner)) {
    return true;
  }
  final comments = StringBuffer();
  var inBlock = false;
  for (final raw in const LineSplitter().convert(source)) {
    final line = raw.trim();
    if (inBlock) {
      comments.write(' $line');
      inBlock = !line.contains('*/');
    } else if (line.startsWith('///')) {
      continue;
    } else if (line.startsWith('//')) {
      comments.write(' $line');
    } else if (line.startsWith('/*')) {
      comments.write(' $line');
      inBlock = !line.substring(2).contains('*/');
    } else if (line.isNotEmpty) {
      break;
    }
  }
  return _banner.hasMatch(comments.toString());
}

String _readPrefix(File file, int maxChars) {
  try {
    final content = file.readAsStringSync();
    return content.length <= maxChars
        ? content
        : content.substring(0, maxChars);
  } on FileSystemException {
    return '';
  }
}
